compressionLevel: 0

enableGlobalCache: true

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: "@yarnpkg/plugin-version"
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
